version: '2.2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: modee:latest
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  cam_node:
    image: modee:latest
    container_name: cam_node
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=cam_node"
      - "DISPLAY=unix$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >      
      bash -c "source /opt/ros/noetic/setup.bash &&
      rosrun usb_cam usb_cam_node _pixel_format:="yuyv" _autofocus:=false _focus:=500 _framerate:=30 _sharpness:=0 _contrast:=32"
    privileged: true
    restart: always

  dev-container:
    image: modee:latest
    container_name: dev-container
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=dev-container"
      - "DISPLAY=unix$DISPLAY" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - ~/github/modee:/root/catkin_ws/src/modee
    command: tail -F anything
    privileged: true
    restart: always