version: '2.2'

# networks:
#   ros:
#     driver: bridge

services:
  ros-master:
    image: modee:latest
    container_name: ros-master
    command: stdbuf -o L roscore
    # networks:
    #   - ros
    # environment:
    #   - "ROS_MASTER_URI=http://ros-master:11311"
    #   - "ROS_HOSTNAME=ros-master"
    network_mode: "host"
    restart: always

  cam-node:
    image: modee:latest
    container_name: cam-node
    depends_on:
      - ros-master
    # networks:
    #   - ros
    # environment:
    #   - "ROS_MASTER_URI=http://ros-master:11311"
    #   - "ROS_HOSTNAME=cam_node"
    #   - "DISPLAY=unix$DISPLAY"
    network_mode: "host"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >      
      bash -c "source /opt/ros/noetic/setup.bash &&
      rosrun usb_cam usb_cam_node _pixel_format:="yuyv" _autofocus:=false _focus:=500 _framerate:=30 _sharpness:=0 _contrast:=32"
    privileged: true
    restart: always

  ocr-node:
    image: ocr:latest
    container_name: ocr-node
    depends_on:
      - ros-master
    # networks:
    #   - ros
    environment:
    #   - "ROS_MASTER_URI=http://ros-master:11311"
    #   - "ROS_HOSTNAME=ocr-node"
      - "DISPLAY=unix$DISPLAY" 
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - ~/github/ocr:/root/catkin_ws/src/ocr
    command: >      
      bash -c "source ~/catkin_ws/devel/setup.bash &&
      rosrun ocr ocr_node.py"
    privileged: true
    restart: always

  modee-dev-container:
    image: modee:latest
    container_name: modee-dev-container
    # networks:
    #   - ros
    network_mode: "host"
    environment:
      # - "ROS_MASTER_URI=http://ros-master:11311"
      # - "ROS_HOSTNAME=modee-dev-container"
      - "DISPLAY=unix$DISPLAY" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - ~/github/modee:/root/catkin_ws/src/modee
    command: tail -F anything
    privileged: true
    restart: always

  ocr-dev-container:
    image: ocr:latest
    container_name: ocr-dev-container
    # networks:
    #   - ros
    environment:
      # - "ROS_MASTER_URI=http://ros-master:11311"
      # - "ROS_HOSTNAME=ocr-dev-container"
      - "DISPLAY=unix$DISPLAY" 
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - ~/github/ocr:/root/catkin_ws/src/ocr
    command: tail -F anything
    privileged: true
    restart: always

  # inception-v3-dev-container:
  #   image: inception-v3:latest
  #   container_name: inception-v3-dev-container
  #   networks:
  #     - ros
  #   environment:
  #     - "ROS_MASTER_URI=http://ros-master:11311"
  #     - "ROS_HOSTNAME=inception-v3-dev-container"
  #     - "DISPLAY=unix$DISPLAY" 
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - ~/github/inception_v3:/root/catkin_ws/src/inception_v3
  #   command: tail -F anything
  #   privileged: true
  #   restart: always

